---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mariadb
    - php-mysql

- name: Download MediaWiki
  get_url:
    src: "path for mediawiki package"
    dest: /tmp/

- name: Moving MediaWiki to web directory
  command: creates={{ wiki.install_path }} mv /tmp/mediawiki-version/ {{ wiki.install_path }}

- name: Configuring MediaWiki
  template:
    src: LocalSettings.php.j2
    dest: "{{ wiki.install_path }}/LocalSettings.php"
    mode: 0644

- name: Updating permissions on MediaWiki installation
  file:
    path: "{{ wiki.install_path }}"
    recurse: yes
    mode: 0775