---
- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mariadb
    - php
    - php-pear
    - php-xml
    - php-mysql
    - php-intl
    - php-gd
    - php-mbstring

- name: Download MediaWiki
  get_url:
    url: http://releases.wikimedia.org/mediawiki/1.24/mediawiki-1.24.1.tar.gz
    dest: /tmp/mediawiki.tgz

- name: Unarchive MediaWiki
  unarchive:
    src: /tmp/mediawiki.tgz
    dest: /tmp
    owner: root
    group: root

- name: Moving MediaWiki to web directory
  command: creates={{ wiki.install_path }} mv /tmp/mediawiki-1.24.1/ {{ wiki.install_path }}

- name: Setting up /wiki endpoint and securing wiki from IP address scanning
  template:
    src: wiki.conf.j2
    dest: /etc/httpd/conf.d/wiki.conf
    owner: root
    group: root
    mode: 0664

- name: Configuring MediaWiki
  template:
    src: LocalSettings.php.j2
    dest: "{{ wiki.install_path }}/LocalSettings.php"
    owner: root
    group: root
    mode: 0644

- name: Updating permissions on MediaWiki installation
  file:
    path: "{{ wiki.install_path }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0775